### ISSUE TITLE
RFC - Strategic direction - native Julia packages

### ISSUE THREAD

**Issue by sbromberger** [JuliaWeb/Roadmap#1]
Proposal: 
1.  new packages should be as "pure Julia" as possible, minimizing any external code/dependencies, and 
2.   existing packages that survive "rationalization" should be rewritten/updated to reduce dependencies on external code.

**Comment by aviks** [comment]
I tried to enumerate the native dependencies of the JuliaWeb projects

HTTPClient is based on libCurl. That should probably be put in maintainance mode, and point users to Requests.jl . 

Requests.jl and HTTPServer uses GNU TLS for SSL requests. I don't think that will go away. 

HTTPServer uses Joyent's http-parser C library. This is a performance and security sensitive part of the process, and should probably should not be re-written. 

What else have I missed?

**Comment by amitmurthy** [comment]
http://pkg.julialang.org/ could clearly list the officially blessed packages, i.e., being developed under the JuliaLang umbrella. We can do this by grouping packages accordingly - JuliaWeb, JuliaStats, JuliaParallel, etc. And a separate section for all other independently developed packages.

HTTPClient.jl ought to be moved out from JuliaWeb (as also redirecting on the README). Currently, a newcomer looking for an HTTP client will automatically choose HTTPClient, just based on the name.

**Comment by sbromberger** [comment]
> Requests.jl and HTTPServer uses GNU TLS for SSL requests. 

Just to clarify. Both of these require GnuTLS.jl.

> I don't think that will go away.

It means that 1) GnuTLS provides the foundation for several other critical packages, which therefore implies that 2) bugs in the GnuTLS package probably need to be given priority over "leaf packages".

**Comment by sbromberger** [comment]
@amitmurthy I guess (based on the commit history) you're the primary author of HTTPClient.jl - just to confirm you're ok with deprecating HTTPClient.jl in favor of Requests.jl? Is there any functionality that the former provides that the latter does not?

**Comment by amitmurthy** [comment]
I have no issues. Just to note:
- HTTPClient uses libcurl  (http://curl.haxx.se/ ) which is a very mature library and has support for almost anything HTTP related - handling redirects, various authentication schemes, proxies, etc, etc.
- I have not looked at Requests.jl in detail, but, I suspect, it will take quite some time for it to match cURL in terms of features - which is not to say that it is not good enough for the vast majority of use cases - which just require simple HTTP calls.
- Requests.jl is currently better integrated with the event loop (libuv). The issues mentioned in https://github.com/JuliaLang/julia/pull/4401 is holding back HTTPClient.jl from doing the same - it uses a workaround based on calling back libcurl at regular intervals.
- IMO, "pure julia" need not be a driver for deprecating HTTPClient (Julia itself depends on lots of external packages), but the fact that the rest of the web stack is more Joyent / GnuTLS based, will make it easier for the community to support an "official" HTTP client that use the same stack.
- `HTTPClient.jl` can live on outside the official webstack for folks looking for feature completeness. A pity about the name though. Too late to clean that up.

**Comment by sbromberger** [comment]
@amitmurthy could you do me a favor if you have some spare time and check to see how libcurl handles EOF? That is, at a lower level than an HTTP session (think TLS) - when a check for EOF  is performed on a stream that has no bytes, is there a delay? (I'm seeing one in GnuTLS that's very annoying and am wondering whether it's just part of the game.)

**Comment by sbromberger** [comment]
Just a note: SMTPClient is also using LibCURL.

**Comment by aviks** [comment]
Yes indeed, SMTPClient uses libCurl. I would be more than happy to deprecate it if we get  a reasonable SMTP client library in Julia. It was meant to be (and indeed looks like) a quick and dirty solution to an immediate problem.

**Comment by sbromberger** [comment]
@aviks no deprecation at this point. We're running into significant issues with GnuTLS (see https://github.com/JuliaWeb/GnuTLS.jl/issues/39). Not sure how to fix but the whole suite of GnuTLS-derived packages probably needs a makeover.

**Comment by sbromberger** [comment]
Probably best to close this out now that we've got better direction with mbedtls and #10.
