### ISSUE TITLE
Large-scale cleanup of JuliaWeb

### ISSUE THREAD

**Issue by malmaud** [JuliaWeb/Roadmap#10]
In the near future, I'd like JuliaWeb to only contain working and useful packages. Being listed in JuliaWeb should be an indication that that developers of Julia's web infrastructure stand behind the package - both certifying that the package is functional and advocating for its use.

A corollary of that is that we shouldn't have packages that are almost perfect substitutes for each other without a compelling reason. 

I believe the following packages no longer meet that criterion:
- SMTPClient.jl
- LibCURL.jl (this meets the "useful functionality" bar, but is currently broken and needs a maintainer to stay in JuliaWeb).
- HTTPClient.jl
- Meddle.jl
- GnuTLS.jl
- Morsel.jl

They should be moved back to their original developers' private repositories, or perhaps to some kind of "JuliaWebDeprecated" organization.

Meanwhile, depending on @one-more-minute's disposition, Mux.jl could be moved _into_ JuliaWeb. 

Thoughts, @IainNZ, @sbromberger, @quinnj?

**Comment by sbromberger** [comment]
I am very grateful for all the work that's been done (especially by you, @malmaud, and particularly with your drive towards mbedtls, a proposal of which I was initially skeptical) on curating JuliaWeb lately and am in full agreement with your proposal. Let me know how I can help.

**Comment by sbromberger** [comment]
Some thoughts: it would be nice to be able to enumerate the elements of a web/comms stack and figure out where the gaps are. That is, if we deprecate SMTPClient.jl, we have no out-of-the-box solution for sending mail easily. I'm not suggesting that this influence the decision as to whether or not to deprecate, but we should identify functionality that doesn't exist / no longer exists and perhaps prioritize replacements.

**Comment by malmaud** [comment]
Thanks Seth! WRT mbedtls, I still think it would be great to having a robust OpenSSL wrapper package and make Requests.jl and HttpServer.jl agnostic with respect to the ssl backend - that's just not something I personally have the motivation to work on.

**Comment by quinnj** [comment]
+100 to deprecating all those packages.

I also agree with @sbromberger's suggestion to identify the "gaps in functionality"; I think we could put it all in a "Up For Grabs" type issue/document/roadmap somewhere in the case where somebody wants to dive in and help.

Didn't hte invenia guys work on an smtp client recently? Am I remembering that wrong?

**Comment by MikeInnes** [comment]
Yes, I'll second that @malmaud's work on JuliaWeb has been awesome – and this plan looks like it will leave things in really good shape.

I'm happy to send Mux over to JuliaWeb, although it looks like I need admin rights to the org to do so.

**Comment by IainNZ** [comment]
@one-more-minute I've granted those now

I think definitely preferable that packages go back to their creators if possible, so

**Comment by IainNZ** [comment]
SMTPClient.jl - @aviks 
LibCURL.jl (this meets the "useful functionality" bar, but is currently broken and needs a maintainer to stay in JuliaWeb) - @amitmurthy 
HTTPClient.jl - @amitmurthy 
Meddle.jl - Hacker School, not sure who would be willing to take it
GnuTLS.jl - This does seem to sort of work? Not sure if we have to move it out. @Keno 
Morsel.jl - Same as Meddle

**Comment by sbromberger** [comment]
Is it possible to have a folder of repos within an organization? (If so, perhaps we can move the hacker school stuff into one called "Deprecated" or something).

**Comment by MikeInnes** [comment]
Cheers @IainNZ. Since there didn't seem to be any objections I've gone ahead and moved Mux into JuliaWeb.

**Comment by IainNZ** [comment]
@sbromberger there are teams for human beings, but no such distinction for repos. As you can see for Meddle and Morsel, I've put big deprecated warnings in the readme, and in the repo description - that is maybe sufficient. Moving them out would be even better IMO, if it goes back to the owner.

**Comment by malmaud** [comment]
My only motivation really for wanting to move them into a deprecated organization is so they wouldn't be visible on the JuliaWeb landing page. I'm worried it sends a bad message if people come to JuliaWeb and see big DEPRECATEd warnings all over - they might assume it reflects on the general state of the organization rather those specific packages.

**Comment by IainNZ** [comment]
Yeah its not a great look

**Comment by IainNZ** [comment]
Also, don't forget http://juliawebstack.org/ is still lurking in the JuliaLang org

**Comment by sbromberger** [comment]
so - create a DeprecatedJuliaPackages organization? :)

Other thoughts: probably want to make updates to @svaksha's [curated decibans](https://github.com/svaksha/Julia.jl) list.

**Comment by malmaud** [comment]
Wow, did not even know about that site.

The only real hurdle to the deprecated organization idea is that teams are not cross-organizational AFAIK, so all the access control to the packages would have to be made redundantly in the new organization.

**Comment by sbromberger** [comment]
The other idea is to figure out if there's a primary committer for these deprecated packages, and ask them what they'd like to do. For example,

Meddle.jl: @IainNZ and @astrieanna are the top two contributors, and
Morsel.jl: @danielmendel and @zachallaun are the top two (with Iain as number 3).

**Comment by svaksha** [comment]
On Sun, Oct 25, 2015 at 4:33 PM, Seth Bromberger
notifications@github.com wrote:

> Other thoughts: probably want to make updates to @svaksha's curated decibans list.

PR's welcome: https://github.com/svaksha/Julia.jl/blob/master/Web-Server.md#org-juliaweb

SVAKSHA ॥  http://about.me/svaksha  ॥

**Comment by malmaud** [comment]
If there aren't objections, I'm thinking we pull the trigger on this one week from now - any unclaimed deprecated packages will get moved to https://github.com/JuliaDeprecated.

**Comment by astrieanna** [comment]
I'm happy with the Meddle/Morsel stuff going to a deprecated org. It was originally developed in the HackerSchool org, and I don't know that any one person is really the "owner".

I'm really glad you're going through and deprecating/removing stuff. :+1:

**Comment by malmaud** [comment]
Cool, thanks! 

Just for posterity, let me note that I do appreciate all the work that went into the packaged that are being deprecated, including the work of the HackerSchool people.

**Comment by svaksha** [comment]
@malmaud, will [JuliaDeprecated](https://github.com/JuliaDeprecated) be the place holder for all the deprecated Julia packages or only contain JuliaWeb packages?

**Comment by malmaud** [comment]
My thinking is the former, but only when the original developer of a
package that is now hosted in an organization doesn't want it back - I
think that should be relatively rare.

**Comment by svaksha** [comment]
Thanks for the clarification.

**Comment by aviks** [comment]
I'm happy to take back SMTPClient.jl. I still use it.  @malmaud can you make me owner of JuliaArchive temporarily?

**Comment by malmaud** [comment]
Great; I sent you a request to accept a transfer.

**Comment by amitmurthy** [comment]
I think HTTPClient and LibCURL should continue to stay under JuliaWeb. HTTPClient and LibCURL do work under Unix but may be broken under Windows.

If the community feels otherwise, I am happy to take them back. No issues.

**Comment by malmaud** [comment]
I think everyone appreciates the utility of LibCURL, but

1) it's failing its tests,
2) still says httpclient.jl in its license
3) has sparse documentation, especially its readme

It would be great if someone fixed those things so it wouldn't be
problematic to have it stay.

**Comment by amitmurthy** [comment]
> 1) it's failing its tests,

The tests are calling HTTPClient. I'll change it to just test loading of the LibCURL library.

> 2) still says httpclient.jl in its license

Will change.

> 3) has sparse documentation, especially its readme

Since it is a wrapper, the doc will point to libcurl's doc. Will explain it further.

**Comment by malmaud** [comment]
Sounds great.

**Comment by malmaud** [comment]
Alright, looks like this is settled now. tl;dr for future reference:
- smtpclient ended up with @aviks 
- httpclient is being updated by @amitmurthy 
- meddle and morsel have moved to the new juliaarchive org

**Comment by PallHaraldsson** [comment]
@IainNZ "Also, don't forget http://juliawebstack.org/ is still lurking in the JuliaLang org"

Yes, seems seriously outdated.. Are same people responsible for it? Not sure where to bring that up.

[ https://github.com/shashi/Escher.jl could also be mentioned there, I haven't used, just seems cool, while sadly http://escher-jl.org/ link is not a good one.. still blanks in seconds.. a problem not related to Escher.jl.

https://github.com/essenciary/Genie.jl is new, too new to mention?]
