### ISSUE TITLE
Seeking mentor for GSoC 2016 project HTTP2 Implementation.

### ISSUE THREAD

**Issue by sarvghotra** [JuliaWeb/Roadmap#13]
I want to apply to apply to GSoC. I posted it on Julia-user google group [here](https://groups.google.com/forum/#!topic/julia-users/GhcdolIPNu4) but didn't get any response from any potential mentor for [HTTP2 Implementation](http://julialang.org/soc/ideas-page#http2-implementation) project, for other project I did get one.

I have some experience while contributing to Julia for months now.

Please reply soon because 25/03/2016 is the deadline for proposal submission.

Thank you.

**Comment by MikeInnes** [comment]
Just as a heads up, we've relaxed the guidelines a bit so that finding a mentor isn't absolutely essential. If you focus on putting together a really good application then we can find a mentor for you.

**Comment by sarvghotra** [comment]
Cool.
Thanks.
