### ISSUE TITLE
State of JuliaWeb

### ISSUE THREAD

**Issue by IainNZ** [JuliaWeb/Roadmap#2]
Heres how I see the state of JuliaWeb right now: too many packages, not enough developers. This isn't a criticism of anyone, more just a concerning state of affairs that I'd like to find a way out of. A lot of these packages are pretty important.
- I think there are some opportunities for rationalization. 
  - For example, Requests.jl and HTTPClient.jl doing the exact same thing, in different ways. Would be best to pick one and concentrate efforts I think, especially as Requests.jl is one of the most depended on packages.
  - URITemplate.jl could possibly be merged into URIParser.jl?
- Morsel/Meddle are neat, but are currently receiving very little love. Morsel is actually one of the top 10 Julia packages by :star:s, and I'm not sure if it even works properly.
- GnuTLS.jl is a very important package, but it isn't even passing tests right now, and I think there is approximately 1 person who understands the package.

I think it'd be great getting more developers at least getting more familiar with these packages, and giving them a polish. 

Side note: I do feel bad about saying "someone should do something!" because I don't believe thats the open source way, but I've got too many other packages that I do use in my work to think about + PkgEval stuff.

**Comment by sbromberger** [comment]
Thanks, @IainNZ - this is an important discussion.

My $0.02:

We should define a suite of "web-relevant" functionality we want to support. I think that there are different layers of the stack that belong in JuliaWeb. These include the following (note that packages may already exist for some/most/all of these):

_General_
1) Consistent Network / URI data representation
2) Consistent socket approach (maybe already in Base?)
3) JSON and other common data representations
4) Safe (security-wise) string and user input/output routines

_Client_
1) URI requests exposing  (get/post/options/...) fundamentals.
2) a REST package (implementing CRUD on top of 1) - I confess that this needs more thought)
3) Websockets
4) Possibly 0MQ or something like it?

_Server_
1) An HTTP server with middleware and dynamic routing
2) A REST server package (more thought required)
3) Websockets / other connection persistence

There's undoubtedly more - but if we can figure out what we want to support, then we have a better chance of making correct technology selections / requests for help.

**Comment by randyzwitch** [comment]
How do API wrappers fit into our definition? Are we just talking infrastructure, or would packages like [Twitter.jl](https://github.com/randyzwitch/Twitter.jl), [Yelp.jl](https://github.com/quinnj/Yelp.jl), Google Analytics (when I get around to writing it) fit here as well?

I've been meaning to do more work on the package for completeness, but I factored out the [OAuth](https://github.com/randyzwitch/OAuth.jl) code from my Twitter package, and it seems like it fits under this umbrella.

**Comment by sbromberger** [comment]
@randyzwitch my personal opinion: I'd like to see those in here as well, as they provide solutions to the general "here's how you get stuff from the internet into Julia" problem.

**Comment by randyzwitch** [comment]
@sbromberger I agree with you. I'll keep my remaining packages in mind for moving to JuliaWeb, once I'm comfortable/have time to make changes.

Another idea: If we're going to pick single 'best' packages like Requests.jl, does it make sense to consolidate HttpCommon into Requests? The idea of lots of little focused packages makes them easy to update (in theory), but at the same time, if we bundle the common functions inside the community-supported package, it seems like it would make things easier and more obvious.

**Comment by sbromberger** [comment]
@randyzwitch If there are cases where HttpCommon can be used independently, then perhaps it should stay separate? I can see it being used for Requests, and for HttpServer, and possibly others, in which case it seems inappropriate to have HttpServer, as an example, have to require Requests.

The weird thing about HttpCommon and Requests is that it's not in the REQUIRE file, but it's a "using" statement in the source. Requests definitely needs a review.

**Comment by randyzwitch** [comment]
Good point, I wasn't thinking of the server side of things. 

My original thought was that I import HttpCommon and Requests, but only to extend the `encodeURI` function from HttpCommon. But you're right, encode/decode functions are useful on both ends of the requesting/serving spectrum.

**Comment by hayd** [comment]
Also https://github.com/one-more-minute/Mux.jl. It would be interesting to see a lightweight/flask-like framework built on top of Mux... Is anyone already working on one?

**Comment by JockLawrie** [comment]
While not exactly a framework, I am working on a tutorial for [web development in Julia](https://bitbucket.org/jocklawrie/skeleton-webapp.jl/src/fae46c05fbaf7921a86616bcaf565ebf5a241239/docs/outline.md?fileviewer=file-view-default). A few notes:
- This project essentially documents my own learning, which I hope others might find useful.
- Examples 4-6 will hopefully be implemented over the next few weeks
- So far I have had no need for middleware because I have found HttpCommon.jl and HttpServer.jl to be quite accessible as is. That is, the resulting app() functions in the examples make the apps' behaviour crystal clear without the need for additional dependencies. This may change as the need arises, which would then highlight the distinction between situations that require middleware and those that don't. Comments/suggestions always welcome.

**Comment by JockLawrie** [comment]
...the point being that at this stage, given the limited supply of labour, I think a set of working examples using the existing packages is a higher priority than a new package.

**Comment by IainNZ** [comment]
@JockLawrie that sounds very sensible, and I also thinking describing and characterizing the basics comprehensively is a great idea.

**Comment by IainNZ** [comment]
Team, the state of JuliaWeb has meandered a lot from when I first made it, so I'm going to close it in favor of more targeted discussion.

**Comment by EricForgy** [comment]
Hi JockLawrie,

I think I am the exact target audience for your tutorial and remember seeing an earlier version of it. I will definitely work through it. I have been meaning to ask a general question though and your third bullet point above pushes me to ask it (before reading the tutorial - dangerous!).

I have 20+ years working with Matlab including some web-based work (taking advantage of the fact you can embed Java in m-files) and now I am hoping to build Julia web apps. I was a little sad to see Morsel.jl abandoned, but really, the feature I used from Morsel was routing and I liked the way it worked. I plan to give Mux.jl a try, but was wondering if I could ask about "best practices" for routing. Is just HttpCommon and HttpServer sufficient?

I need enterprise quality technology suitable for large financial institutions.
