### ISSUE TITLE
Possible plan to rename packages

### ISSUE THREAD

**Issue by IainNZ** [JuliaWeb/Roadmap#3]
It was proposed to rename some packages in JuliaWeb:
- HttpCommon -> HTTPCommon or HTTPCommons (https://github.com/JuliaWeb/HttpCommon.jl/issues/18)
- HttpServer -> HTTPServer or HTTPServers (https://github.com/JuliaWeb/HttpServer.jl/issues/43)
- HttpParser -> HTTPParser or HTTPParsers (https://github.com/JuliaWeb/HttpParser.jl/issues/29)

Most past discussion happened here: https://github.com/JuliaWeb/HttpCommon.jl/issues/18. As you can see, I am not in favor of this change because I don't think that the gain in consistency is worth the broken code.

**Comment by sbromberger** [comment]
In favor of capitalizing HTTP, but not pluralizing unless we're planning on implementing multiple types of server / parser (which I am not right now in favor of doing).

**Comment by aviks** [comment]
Changing a name just by capitalising might cause a great deal of pain for users of braindead case insensitive file systems (_cough_mac*cough), afaik.

**Comment by jballanc** [comment]
In the grand tradition of `XMLHttpRequest`, I'd argue that leaving "Http" with initial-caps is allowable, even when you're all-caps-ing other acronyms.

**Comment by sbromberger** [comment]
@jballanc See, e.g., https://en.wikipedia.org/wiki/Naming_convention_(programming)#Common_elements for a discussion:

> Treatment of acronyms in identifiers (e.g. the "XML" and "HTTP" in XMLHttpRequest) varies. Some dictate that they be lowercased (e.g. XmlHttpRequest) to ease typing and readability, whereas others leave them uppercased (e.g. XMLHTTPRequest) for accuracy. A less popular option is to always expand any acronyms (e.g. ExtensibleMarkupLanguageHyperTextTransferProtocolRequest).

**Comment by IainNZ** [comment]
This isn't going to happen until the next version of `Pkg` enables renaming, if ever. Too much churn.
