### ISSUE TITLE
multithreaded HttpServer

### ISSUE THREAD

**Issue by ssagaert** [JuliaWeb/Roadmap#4]
Once SMP multithreading becomes available in julia, I'd like to see HttpServer running on a threadpool (with nr. threads = nr of cores) so that the server can actually use all cores of a machine.

**Comment by IainNZ** [comment]
This isn't necessarily a good idea, c.f. node.js

**Comment by ssagaert** [comment]
async io is good but isn’t a catch all solution even in node.js you can do multicore processing (granted only via processes not threads) see e.g. http://blog.carbonfive.com/2014/02/28/taking-advantage-of-multi-processor-environments-in-node-js/
or
http://nodejs.org/api/cluster.html

**Comment by IainNZ** [comment]
Julia has multiprocessing though? Seems like that could be done right now

**Comment by ssagaert** [comment]
yes but I’d prefer a multithreaded version for the following reason:

Imagine you hold a large data model (think GBs) in memory and the web application basically queries that data model (I have a julia web app like that). If it’s multithreaded all threads can access that model. If it’s multiprocess then either each process has a copy  => you’ll quickly run out of physical RAM memory, or one master process holds the datamodel and worker processes have to query the master process but then you’re basically in a similar situation with the async request handling in that the master becomes a bottleneck (& a single point of failure). Also if the application wants to update the model then even if you use multiprocess it will still have to use some form of locking/synchronization just like with multithreading. Note that I’m not saying that async should be given up. The solution would be async + multicore. Also : ideally the multithreaded julia model will be high level so that users themselves do not have to bother with low level threading API issues like locking. 

Van: Iain Dunning
Verzonden: ‎zondag‎ ‎15‎ ‎februari‎ ‎2015 ‎18‎:‎17
Aan: JuliaWeb/Roadmap
CC: Steven Sagaert

Julia has multiprocessing though? Seems like that could be done right now

**Comment by IainNZ** [comment]
Closing this. PRs welcome on HttpServer.jl when and if this becomes feasible.
