### ISSUE TITLE
Fix or (deprecate and replace) GnuTLS

### ISSUE THREAD

**Issue by sbromberger** [JuliaWeb/Roadmap#5]
GnuTLS.jl is the core of a bunch of other JuliaWeb packages but it's not stable at this point, and this results in the other packages failing intermittently (and without any consistency). Since this is a roadmap issue, I'd like to suggest we set a direction here:

1) Confirm GnuTLS as the appropriate package for TLS / secure communications, and put effort into fixing it (and making sure it keeps in sync with libgnutls); or
2) Deprecate GnuTLS and seek a replacement that will be as easy (or easier) to maintain.

**Comment by sbromberger** [comment]
I've spent the last two days trying to understand gnutls and have come to the conclusion that we can probably make it work, but there is some puzzling behavior (i.e., a ~10 second timeout when checking for eof on the stream.) I think @keno's expertise would be very valuable here.

**Comment by sbromberger** [comment]
Just noticed that the julia build process (in the git section) uses libopenssl. Is there any advantage to standardizing?

**Comment by hayd** [comment]
http://www.zdnet.com/article/gnutls-big-internal-bugs-few-real-world-problems/

IMO it's best to use the industry standard: OpenSSL. There's https://github.com/dirk/OpenSSL.jl and https://github.com/amitmurthy/OpenSSLCrypto.jl but both need some love.

**Comment by sbromberger** [comment]
Having spent the better part of a day wrestling with this (see https://github.com/JuliaWeb/GnuTLS.jl/issues/39 for the latest problem), I'm inclined to agree. I wonder if the licensing presents an issue.

**Comment by hayd** [comment]
Licensing should be better with OpenSSL (it's BSD) which is MIT compatible. MIT being the Julia license and how the majority of packages are licensed. :)

Perhaps @dirk or @amitmurthy have some thoughts on OpenSSL/their packages.

**Comment by sbromberger** [comment]
copying @dls on this as well since there's another openssl package there. All 3 are focused right now on crypto; what we need for JuliaWeb is the TLS stuff.

@dls, @amitmurthy, and @dirk - any chance you three could collaborate on implementing TLS in one robust OpenSSL package that we could then use as the basis for future JuliaWeb efforts?

edited to add @jballanc since he's volunteered to help :)

**Comment by dirk** [comment]
To be honest I haven't touched OpenSSL in Julia in a while, but since then I've gotten some experience hooking it into Rust/C/Node.js. With that said, I'd be up for collaborating with you all to get TLS support integrated into one main OpenSSL package!

**Comment by amitmurthy** [comment]
I tinkered with OpenSSL for some request signing part required in AWS.jl - it mostly wrapped openssl using Clang.jl. At this time I don't have plans to develop it further - I also don't have the required background in crypto to design a good higher level interface.

**Comment by stevengj** [comment]
IJulia uses Nettle (for hashing); we gave up on GnuTLS early on because of general flakiness.

**Comment by quinnj** [comment]
I'm in sore need of really reliable HTTPS, so I'm committed to helping figure the TLS situation out. Is it worth taking https://github.com/dirk/OpenSSL.jl further or starting from scratch? @sbromberger, you mentioned seeing libopenssl in the julia build process, is that true? Where is it located for you? I wasn't aware/can't find it in my source build.

**Comment by Keno** [comment]
The problem with OpenSSL (which I just remembered) and the reason that I originally went for GnuTLS was that OpenSSL is GPL incompatible.

**Comment by quinnj** [comment]
Hmm....it seems @hayd was mistaken somehow. What about a lightweight library like https://tls.mbed.org/source-code; their license is GPL but it also adds something about FOSS, which I'm not familiar with.

**Comment by hayd** [comment]
I think this was my error (according to [wikipedia](http://en.wikipedia.org/wiki/OpenSSL)):

> The common usage of the term dual-license is that the user may pick which license they wish to use. However, OpenSSL documentation uses the term dual-license to mean that both licenses apply.

That sucks - sorry for the misinformation. (see also [SO question](http://stackoverflow.com/questions/6720610/when-and-where-to-mention-usage-of-openssl))

**Comment by quinnj** [comment]
Ok, I'm thinking of doing a port of a popular python library [tlslite](https://github.com/trevp/tlslite/tree/master/tlslite). Good license, straightforward implementation, Google has contributed to it. Let me know if anyone wants to jump in and help.

**Comment by sbromberger** [comment]
I don't understand the licensing issue. OpenSSL is essentially the Apache license, which is freer than GPL. (See http://openssl.org/source/license.html). Why are we throwing away a well-vetted, almost-universally-adopted standard because of some possibly contrived issue?

Everyone's free to do what they'd like, of course, but I've got a GSOC project in the works to get bindings for OpenSSL. It would be nice (but again, not necessary, I guess) if we could rally around a single backend package, preferably one that is well-known and well-vetted.

**Comment by sbromberger** [comment]
@quinnj here's an extract from `grep -Ri openssl *` from the julia source:

```
deps/libgit2-0.22.0/build/CMakeFiles/git2.dir/C.includecache:../include/git2/sys/openssl.h
deps/libgit2-0.22.0/build/CMakeFiles/git2.dir/C.includecache:hash/hash_openssl.h
deps/libgit2-0.22.0/build/CMakeFiles/git2.dir/C.includecache:../src/hash/hash_openssl.h
deps/libgit2-0.22.0/build/CMakeFiles/git2.dir/C.includecache:../src/hash/hash_openssl.h
```

**Comment by Keno** [comment]
I don't think the licensing situation is particularly contrived. At best it's ambiguous, which means lots of people will have to avoid it. The problem is that OpenSSL is Apache v1.0 not v2.0, which has been well established is incompatible with the GPL, meaning you can not ship GPL software (e.g. julia currently due to GPL dependencies with OpenSSL). The libgit2 thing is interesting, we should look into that.

**Comment by sbromberger** [comment]
It's not only libgit2, it's the python dependency as well, and virtualenv/pip. Basically, it's unavoidable these days, and Julia's using it.

I also think that if this were a bigger issue for GPL software, you wouldn't see so many GPL-based systems using it (think basically any Linux variant these days, though you do have some GnuTLS holdouts that don't want a "non-free" section). They've all managed to carve out exceptions. Julia should be able to do similar.

**Comment by Keno** [comment]
I don't think saying we have a dependency on python is reasonable. I also don't think there's anything wrong with having an OpenSSL.jl package. There is plenty of use cases when license compatibility is not a concern. All I'm saying is such a package could not be shipped with julia as currently the julia distribution itself is GPL. That's the reason I originally picked GnuTLS.

**Comment by sbromberger** [comment]
@keno perhaps I'm misreading the following (again, extracted via grep) - this looks like pygments rather than python, I guess...

```
deps/julia-env/lib/python2.7/site-packages/pygments/lexers/_php_builtins.py:             'openssl_private_encrypt',
deps/julia-env/lib/python2.7/site-packages/pygments/lexers/_php_builtins.py:             'openssl_public_decrypt',
deps/julia-env/lib/python2.7/site-packages/pygments/lexers/_php_builtins.py:             'openssl_public_encrypt',
```

And I agree with you about not including this in the julia distribution (I'm assuming you mean Base and the code surrounding it). If that's the primary issue, then I think JuliaWeb can standardize on OpenSSL as long as the packages are independent of Base with appropriate and conforming license notifications.

**Comment by quinnj** [comment]
Would it be better to dig into gnuTLS some more to make it more stable? I guess I thought there were licensing issues with that as well, but I just double-checked and it looks ok. Can't we try and make gnuTLS the standard?

**Comment by sbromberger** [comment]
Also, wait a second: Julia's license is MIT, not GNU, and there are TONS of exceptions:

https://github.com/JuliaLang/julia/blob/master/LICENSE.md

What am I missing?

**Comment by Keno** [comment]
I believe that's just used for documentation, so it's fine because we're not distribution it. The concern I had was that if we ever decide to standardize a set of packages to ship with julia, an OpenSSL package probably couldn't be part of it. Also any `JuliaWeb` distributions would have to avoid GPL'd packages. I realize this isn't ideal. I do believe OpenSSL (or even better LibreSSL) is the better technical choice, but I chose GnuTLS because of licensing.

**Comment by Keno** [comment]
Julia is MIT, but it has dependencies on GPL'd software, so the binary distribution falls under the GPL because the GPL is viral.

**Comment by sbromberger** [comment]
@quinnj GnuTLS is poorly maintained relative to OpenSSL and has not responded well to vulnerability notices (http://www.zdnet.com/article/gnutls-big-internal-bugs-few-real-world-problems/ linked above). I think that the widespread adoption of OpenSSL argues in favor of its use here. I'd much rather depend on OpenSSL (warts and all) for robust security than pretty much any other package out there at this point.

But the beauty of the project is that we can have multiple packages - so if there's some standing objection to using OpenSSL, then by all means, get GnuTLS going.

**Comment by Keno** [comment]
I have no problems with having multiple TLS packages. Let's make sure they have the same julia-side interface though, so we can substitute one for the other if necessary.

**Comment by sbromberger** [comment]
@keno - sorry, I must be dense: what are JuliaWeb distributions?

Also, you likely won't be able to substitute one for the other unless we have a higher-level API. The way setup, negotiation and crypto is done is likely very different between GnuTLS and OpenSSL.

**Comment by Keno** [comment]
I was speaking in hypotheticals, where somebody might want to make an easily installable copy of all the JuliaWeb packages. 

Yes, deciding on a higher level API would be good. I think the best interface here is a Stream that has the standard stream methods and gets encrypted on the fly. Setting up such a stream could be a simple function that just takes the host and port, potentially with support for client certificates, but that's getting fancy.

**Comment by sbromberger** [comment]
Ah, I get it - thanks for the explanation.

And yes - but realize that even stream functionality may be difficult. I'm sure certificate validation is completely different among the various packages (and I wouldn't be surprised to find some of the smaller ones ignoring validation altogether).

Anyway - I'm very happy we're moving on this. If you wouldn't mind, could you open up a separate issue for the API discussion (under this roadmap) and we can figure it out?

**Comment by quinnj** [comment]
@sbromberger, can you add me to the JuliaWeb org? I have a bunch of deprecation fixes I want to push in.

**Comment by sbromberger** [comment]
@quinnj done :) Thanks.

**Comment by quinnj** [comment]
Thanks.

**Comment by quinnj** [comment]
Licensing question: If a C library is released under Apache 2.0; how would that combine with MIT or a possible future state of being bundled with Julia?

**Comment by simonster** [comment]
FWIW, NSS is widely used (by Firefox and, until recently, Chrome) and has a compatible license (MPL 2.0). I have no idea what its API looks like.

**Comment by sbromberger** [comment]
@simonster The fact that it's been FIPS-validated (multiple times) is a bonus, but it requires NSPR which would add some complexity/dependence.

**Comment by aviks** [comment]
@quinnj AFAIK, IANL etc but, 

It is fine to combine an Apache2 licensed library with a GPLv3 distribution. However, the FSF considers the Apache2 license to be incompatible with GPLv2. 

https://www.apache.org/licenses/GPL-compatibility.html
http://www.softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html

I believe combining MIT and Apache2 licenses are fine, but the patent retaliation clause remains controversial. 

I don't believe there are any issues combining MIT and Apache2 licensed code from a copyright perspective, but like the FSF, people have different interpretations of how the Apache2 patent clauses are infectious.

**Comment by PallHaraldsson** [comment]
I read this far:

"I also think that if this were a bigger issue for GPL software, you wouldn't see so many GPL-based systems using it (think basically any Linux variant these days, though you do have some GnuTLS holdouts that don't want a "non-free" section). They've all managed to carve out exceptions. Julia should be able to do similar."

and: "The problem is that OpenSSL is Apache v1.0 not v2.0, which has been well established is incompatible with the GPL, meaning you can not ship GPL software (e.g. julia currently due to GPL dependencies with OpenSSL)."

Note:
https://www.openssl.org/support/faq.html#LEGAL2

"the GPL does not place restrictions on using libraries that are part of the normal operating system distribution" aka GPL's system library exception, that doesn't apply on Windows as it doesn't have OpenSSL.

You can say: "the GPL does not place restrictions on using libraries that are part of the normal operating system distribution" in your wrapper.

BUT, this allows you to use OpenSSL without any other GPL code (unless it also says this, that I do not think, say, Julia's numerical GPL libraries do - I might be wrong).

There might be a way around this, I do not like to be advocating a way around the GPL, I do not think I am. You could put the above in the wrapper and run it in a different process. Your numerical GPL code runs in your other (main) process. If you have a well defined (non-encrypted, but only internal to the machine) API/tunnel between the two processes you are ok with linking anything to the GPL (by their rules).

I'm not sure if the OpenSSL guys are ok with this.. (or if they have a say). Would it be a problem to have an unencrypted tunnel? Could you eavesdrop, only, if you are a superuser (on Windows, this would not be needed mostly everywhere else)? If you are a superuser anyway you can in theory monitor everything inside a process anyway.

**Comment by PallHaraldsson** [comment]
https://github.com/libressl-portable/portable

LibreSSL is in the same situation as OpenSSL, but they dropped a lot of code from OpenSSL (not enough to be Apache 1.0 free it seems) and might have a permissive ("BSD-only") plan in the future.?. at least WP lists these additionally: "ISC License, and some are public domain"

I remembered they didn't like Apache, but it was 1.0 they liked:

http://www.openbsd.org/policy.html
"The original Apache license was similar to the Berkeley license, but source code published under version 2 of the Apache license is subject to additional restrictions and cannot be included into OpenBSD.
[..]
"For historical reasons, the OpenBSD base system still includes the following GPL-licensed components: the GNU compiler collection (GCC) with supporting binutils and libraries, GNU CVS, GNU texinfo, the mkhybrid file system creation tool, and the readline library. Replacement by equivalent, more freely licensed tools is a long-term desideratum."

**Comment by sbromberger** [comment]
I don't think we need to "work around" the GPL. Any library we develop for OpenSSL would not be bundled with any additional GPL software; it would be a package to install with its own (OpenSSL-derived / OpenSSL-compatible) license. I think this avoids the bundling issue to which most folks refer when they talk about GPL / OpenSSL license incompatibility.

In any case, the packages themselves haven't seen much activity lately, and we didn't get our NumFocus GSoC slot, so I'm not sure what the practical net effect of all this discussion is right now :)

See also https://github.com/JuliaLang/julia/issues/10763#issuecomment-90935823

**Comment by PallHaraldsson** [comment]
When I think about it, if this is not going into base, would "Julia as a whole" be considered as an environment and it would fall under the "GPL's system library exception". That is your own code that uses OpenSSL.jl and OpenSSL that comes with it would be ok if you do not make standalone executables?

For standalone distributions of Julia with your code you would however have a problem (when not dropping the optional GPL libraries, except libgit2 I think)..

**Comment by PallHaraldsson** [comment]
"But the beauty of the project is that we can have multiple packages" - I think you mean.. you can use OpenSSL (dynamically chose) on Linux and everywhere where it is preinstalled under the system exception, but:

on Windows you have GnuTLS (with maybe less security..). It's kind of ironic that Windows would get the "GNU"-package that is LGPLv2.1+, because you can use that with the full GPL.. when OpenSSL isn't even GPL.

**Comment by tkelman** [comment]
For Windows we could probably write bindings to the native WinHTTP functionality with whatever license we want just referring to openly available API documentation (or public domain mingw-w64 headers) in the process of writing it, but that would need to be done carefully by someone who knows what they're doing.

**Comment by sbromberger** [comment]
~~Just found this: https://github.com/awslabs/s2n - looks promising.~~

Scratch that:

> At this time s2n does not perform certificate validation and client mode is disabled as a precaution

**Comment by quinnj** [comment]
I still think https://github.com/ARMmbed/mbedtls is probably a good option. Can anyone else verify that it would be able to fully replace GnuTLS? I've been in contact with one of the developers and it sounds like they're flexible on the license (Apache 2.0).

**Comment by sbromberger** [comment]
@quinnj I'd have serious reservations about moving from a less-supported `GnuTLS` to an even-less supported `mbedtls`. IMO, the security benefits of using a widely-adopted package are too important to ignore, especially when we anticipate this package underpinning most, if not all, secure communications in Julia.

**Comment by quinnj** [comment]
"Users include Linksys, Nginx, Government of the Netherlands..."
Their [website](https://tls.mbed.org/security) looks fairly solid along with the "securitiy" center. The developers seem very responsive as I've interacted with them. The commit history [looks plenty strong](https://github.com/ARMmbed/mbedtls/graphs/commit-activity), particularly since ARM took over in February.

Do you have specific concerns about their security or support?

**Comment by hayd** [comment]
Big +1 to mbedtls. If they are flexible on the license all the better!

**Comment by sbromberger** [comment]
I just think that, compared with some of the alternatives, we'd want to go with something that has lots more eyes on the code. It's been my experience that smaller projects may look attractive but having the codebase subjected to multiple formal and informal audits is the way to go for security-sensitive stuff.

The other benefit to going with a big player is that, with a more recognized codebase, we will have potentially more resources available for development, bug fixes, etc.

If the goal is to standardize on something throughout Julia, then I still recommend strongly we go with a widely-adopted codebase - otherwise we'll just find ourselves back with the same challenges we're currently facing with GnuTLS.

ETA: I don't think a history of active commits is a good thing for core security code. It suggests a lack of maturity in the codebase, which is something you don't really want changing all that much to begin with.

**Comment by quinnj** [comment]
Interesting developments all around:
MbedTLS.jl: https://github.com/malmaud/MbedTLS.jl
OpenSSL license updates: https://www.openssl.org/blog/blog/2015/08/01/cla/

**Comment by PallHaraldsson** [comment]
> Interesting developments all around:
> MbedTLS.jl: https://github.com/malmaud/MbedTLS.jl
> 
> [About this. Is MbedTLS the way forward?]

Note, this should help (released yesterday):
https://tls.mbed.org/tech-updates/releases/mbedtls-2.1.0-released-under-apache

MbedTLS.jl is under MIT license with exception (that was removed):
https://tls.mbed.org/foss-license-exception

That is no problem if at least 2.0 is used. Older 1.2 shouldn't be used
anyway, and I'm not sure they can take the exception away retroactively (or
changed that way to Apache 2.0). Not sure if MbedTLS.jl works with the
older version or just both.

**Comment by malmaud** [comment]
Can we close this now? At this point Requests and HttpServer are both using MbedTLS, which is dual-licensed under Apache 2 and GPL 2.

**Comment by hayd** [comment]
I just did a fresh install (and installed Mux) and something is still depending on GnuTLS (though I can't work out what... or maybe one package hasn't had their release in META yet...?).

```
julia> Pkg.add("Mux")
INFO: Cloning cache of BinDeps from git://github.com/JuliaLang/BinDeps.jl.git
INFO: Cloning cache of Codecs from git://github.com/dcjones/Codecs.jl.git
INFO: Cloning cache of Compat from git://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of Dates from git://github.com/quinnj/Dates.jl.git
INFO: Cloning cache of Docile from git://github.com/MichaelHatherly/Docile.jl.git
INFO: Cloning cache of GnuTLS from git://github.com/JuliaWeb/GnuTLS.jl.git
INFO: Cloning cache of Hiccup from git://github.com/JunoLab/Hiccup.jl.git
INFO: Cloning cache of Homebrew from git://github.com/JuliaLang/Homebrew.jl.git
INFO: Cloning cache of HttpCommon from git://github.com/JuliaWeb/HttpCommon.jl.git
INFO: Cloning cache of HttpParser from git://github.com/JuliaWeb/HttpParser.jl.git
INFO: Cloning cache of HttpServer from git://github.com/JuliaWeb/HttpServer.jl.git
INFO: Cloning cache of JSON from git://github.com/JuliaLang/JSON.jl.git
INFO: Cloning cache of Lazy from git://github.com/one-more-minute/Lazy.jl.git
INFO: Cloning cache of MacroTools from git://github.com/one-more-minute/MacroTools.jl.git
INFO: Cloning cache of Mux from git://github.com/one-more-minute/Mux.jl.git
INFO: Cloning cache of Nettle from git://github.com/staticfloat/Nettle.jl.git
INFO: Cloning cache of SHA from git://github.com/staticfloat/SHA.jl.git
INFO: Cloning cache of URIParser from git://github.com/JuliaWeb/URIParser.jl.git
INFO: Cloning cache of WebSockets from git://github.com/JuliaWeb/WebSockets.jl.git
```

**Comment by IainNZ** [comment]
This: https://github.com/JuliaWeb/HttpServer.jl/commit/ab5aafb784da07cebf4db2e5b30b7ff07ed04434
probably wasn't tagged yet

**Comment by IainNZ** [comment]
So it never was really fully fixed, but we've now got MbedTLS instead, so I'll close this in favor of people opening PRs on GnuTLS (if that happens).
