### ISSUE TITLE
add a docroot dir and let HttpServer load static content like images, pdf docs, etc.

### ISSUE THREAD

**Issue by ssagaert** [JuliaWeb/Roadmap#7]
This would be very handy to easily add images, pdfs etc to dynamically generated webpages (now you have to write a webprog itself that load the content from the filesystem and returns it via http and link to that prog). This would be similar to what Tomcat provides.

**Comment by sbromberger** [comment]
I'm actually torn on this idea. Static pages are better served by "real" web servers, since there are some pretty significant security issues related to filesystem access. I guess I'm more in favor of putting the wsgi service behind some sort of other web server that can route appropriately.

**Comment by IainNZ** [comment]
I think Meddle.jl handles this:

```
using HttpServer
using Meddle

stack = middleware(DefaultHeaders, URLDecoder, CookieDecoder, FileServer(pwd()), NotFound)
http = HttpHandler((req, res)->Meddle.handle(stack, MeddleRequest(req, Dict{Symbol,Any}()), res))

for event in split("connect read write close error")
    http.events[event] = (event->(client, args...)->println(client.id,": $event"))(event)
end
http.events["error"] = (client, err)->println(err)
http.events["listen"] = (port)->println("Listening on $port...")

server = Server(http)
run(server, 8000)
```

**Comment by ssagaert** [comment]
Tomcat (in standalone mode) has been doing this for a long time so I don’t see a problem. Of course Tomcat (standalone) lets you configure access.

Van: Seth Bromberger
Verzonden: ‎dinsdag‎ ‎17‎ ‎februari‎ ‎2015 ‎16‎:‎34
Aan: JuliaWeb/Roadmap
CC: Steven Sagaert

I'm actually torn on this idea. Static pages are better served by "real" web servers, since there are some pretty significant security issues related to filesystem access. I guess I'm more in favor of putting the wsgi service behind some sort of other web server that can route appropriately.

**Comment by sbromberger** [comment]
The idea of having to implement some sort of chroot() within Julia gives me indigestion.

**Comment by aviks** [comment]
As @IainNZ  said above, simple static serving is present in Meddle. I doubt, given the current boundaries between these projects, that it would make sense to move these tho `HTTPServer`, since other basic functionality such as header and urls are also in `Meddle`. 

@ssagaert Does that work? Of course, the current functionality is very simple, but we can surely open feature requests in the Meddle repo.

**Comment by ssagaert** [comment]
Maybe.
The reason I used HttpServer directly in my project is because the documentation around Meddle/Morsel is very sparse and I could not see how to do things like send an http error code (I used HttpServer to implement a web API rather than a website).

**Comment by IainNZ** [comment]
Morsel and Meddle are now abandonware - PRs adding functionality and or reviving those packages are welcome.
